name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      run: sudo apt-get install cmake
    - name: Configure
      run: cmake .
    - name: Build
      run: cmake --build .
